const Menu = {
    MenuData: [
        {
            id: 1,
            img: "https://images.pexels.com/photos/9218754/pexels-photo-9218754.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500",
            title: 'Rice Meal',
            desc: 'Although cultures differ, throwing rice at newly wedded couples is regarded as a symbol of good luck, abundance, and fertility. Among the many things’ little girls desire is to have this tradition in their wedding.',
            price: 46,
        },
        {
            id: 2,
            img: "https://images.pexels.com/photos/5410400/pexels-photo-5410400.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Pav Bhaji',
            desc: ' Pav Bhaji originated in the 1850s as a quick and filling lunch option for textile mill workers in Mumbai. It was created by street vendors using leftover vegetables and bread.',
            price: 96,
        },
        {
            id: 3,
            img: "https://images.pexels.com/photos/14530314/pexels-photo-14530314.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Jalebi',
            desc: ' Jalebi is believed to have originated in the Indian subcontinent, with its earliest references dating back to the 13th century. It has since become a cherished dessert in countries like India, Pakistan, Bangladesh, Nepal, and Iran.',
            price: 46,
        },
        {
            id: 4,
            img: "https://images.pexels.com/photos/6808666/pexels-photo-6808666.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Lassi',
            desc: 'Lassi is not only delicious but also nutritious. It is a good source of calcium, protein, vitamins, and minerals. The yogurt used in lassi contains beneficial bacteria that promote a healthy gut flora.',
            price: 46,
        },
        {
            id: 5,
            img: "https://images.pexels.com/photos/12912495/pexels-photo-12912495.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500",
            title: 'Tea',
            desc: 'It takes around 2,000 tiny leaves to make just one pound of tea. There are around 3,000 different types of tea. It is the second most consumed beverage around the world, after water.',
            price: 46,
        },
        {
            id: 6,
            img: "https://images.pexels.com/photos/13063304/pexels-photo-13063304.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Golgappa',
            desc: 'Golgappa is known by different names in various parts of India. It is called pani puri in most regions, puchka in West Bengal and Bangladesh, and golgappa in North India.',
            price: 46,
        },
        {
            id: 7,
            img: "https://images.pexels.com/photos/8887055/pexels-photo-8887055.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Laddu',
            desc: 'Laddu comes in various forms and flavors across different regions of India. Some popular varieties include Besan Laddu (made from chickpea flour), Motichoor Laddu (made from fine boondi), Rava Laddu (made from semolina), Coconut Laddu, and Til Laddu (made from sesame seeds).',
            price: 46,
        },
        {
            id: 8,
            img: "https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Dosa',
            desc: 'In 2014, India set a Guinness World Record for the largest dosa ever made. The dosa measured approximately 16.68 meters (54.72 feet) in length and was cooked in Kerala, India.',
            price: 46,
        },
        {
            id: 9,
            img: "https://images.pexels.com/photos/12946719/pexels-photo-12946719.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500",
            title: 'French Fries',
            desc: 'French fries are popular worldwide and are often prepared and served in various ways. In the United Kingdom, they are known as "chips" and are often served with fish as "fish and chips." In Canada, they are commonly topped with cheese curds and gravy, creating the dish known as poutine.',
            price: 46,
        },
        {
            id: 10,
            img: "https://images.pexels.com/photos/3323680/pexels-photo-3323680.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Pancakes',
            desc: 'Pancakes have their own dedicated day of celebration called "Pancake Day" or "Shrove Tuesday." It falls on the day before the start of Lent in many Christian traditions and is often associated with indulging in pancakes before the fasting period begins.',
            price: 46,
        },
        {
            id: 11,
            img: "https://images.pexels.com/photos/3926123/pexels-photo-3926123.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Momos',
            desc: 'Momos originated in Tibet and were traditionally consumed as a staple food by Tibetans. Over time, they spread to neighboring regions and gained popularity in countries like Nepal, Bhutan, and India.',
            price: 46,
        },
        {
            id: 12,
            img: "https://images.pexels.com/photos/913136/pexels-photo-913136.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
            title: 'Cupcake',
            desc: "In the United States, National Cupcake Day is celebrated on December 15th. It's a day to indulge in and appreciate the deliciousness of cupcakes.",
            price: 46,
        },
    ],
};

export default Menu;